"use strict";
exports.__esModule = true;
var Student_1 = require("./Student");
var quanlisinhvien_1 = require("./quanlisinhvien");
var student1 = new Student_1.Student('tai', 'A', 2);
var student2 = new Student_1.Student('tai2', 'A', 4);
var student3 = new Student_1.Student('tai3', 'A', 6);
var student4 = new Student_1.Student('tai4', 'A', 8);
var student5 = new Student_1.Student('tai5', 'A', 10);
var manager = new quanlisinhvien_1.StudentManager();
manager.addStudent(student1);
manager.addStudent(student2);
manager.addStudent(student3);
manager.addStudent(student4);
manager.addStudent(student5);
var a = manager.startistic();
console.log(a);
// let b = manager.show();
manager.show();
