"use strict";
exports.__esModule = true;
var Book_1 = require("./Book");
var Bookmanager_1 = require("./Bookmanager");
var b1 = new Book_1.Book("s1", "hoc1");
var b2 = new Book_1.Book("s2", "hoc2");
var b3 = new Book_1.Book("s3", "hoc3");
var b4 = new Book_1.Book("s4", "hoc4");
var b5 = new Book_1.Book("s5", "hoc5");
var manager = new Bookmanager_1.Bookmanager();
manager.addBook(b1);
manager.addBook(b2);
manager.addBook(b3);
manager.addBook(b4);
console.log(manager.addBook(b5));
// console.log(manager.findIndex("s3"));
console.log(manager.deleteBook("s3"));
console.log(manager.getBook());
console.log(manager.updateBook("s4", "hoc7"));
console.log(manager.getBook());
